name: Pest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: 'postgres:15'
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: php artisan key:generate
      - run: chmod -R 777 storage bootstrap/cache
      - name: Run pest tests
        env:
          DB_CONNECTION: pgsql
          DB_DATABASE: postgres_db
          DB_PORT: 5432
          DB_USER: postgres_user
          DB_PASSWORD: postgres_password
        run: vendor/bin/pest


