name: Phpinsights

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  phpinsights:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: php artisan key:generate
      - run: chmod -R 777 storage bootstrap/cache
      - name: Run phpinsights
        run: vendor/bin/phpinsights -n --ansi --format=github-action
